<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 ..\..\static\crepi.glb --suspense --transform
Author: Thunder (https://sketchfab.com/thunderpwn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modular-roof-tiles-5697aab59f2b4c49aa304aa2168d6289
Title: modular Roof tiles
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useSuspense } from '@threlte/extras';

	export const ref = new Group();

	export let darkMode = false;

	const suspend = useSuspense();

	const gltf = suspend(useGltf('/crepi-transformed.glb', { useDraco: true }));

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh geometry={gltf.nodes.Roof__0.geometry} rotation={[-Math.PI / 2, 0, 0]}>
			<T.MeshPhysicalMaterial
				clearcoat={.5}
				side={2}
				roughness={1}
				color={darkMode ? 'rebeccapurple' : 'blue'}
			/>
		</T.Mesh>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
