<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 .\static\crep.glb --suspense --transform
Author: SCU Community Heritage Lab (https://sketchfab.com/scu-chl)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/roof-tile-from-mission-santa-clara-09e63a347a8f4baebbab7fb91d83cb84
Title: Roof Tile from Mission Santa Clara
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useSuspense } from '@threlte/extras';

	export const ref = new Group();

	const suspend = useSuspense();

	export let rotation = [0, 0, 0];

	const [rotX, rotY, rotZ] = rotation;

	const gltf = suspend(useGltf('/crep-transformed.glb', { useDraco: true }));

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group scale={[0.009, 0.009, 0.009]} rotation={[rotX + 1, rotY, rotZ + 0.5]}>
			<T.Mesh geometry={gltf.nodes.Object_2.geometry} material={gltf.materials.material_0} castShadow receiveShadow />
			<T.Mesh geometry={gltf.nodes.Object_3.geometry} material={gltf.materials.material_0} castShadow receiveShadow />
			<T.Mesh geometry={gltf.nodes.Object_4.geometry} material={gltf.materials.material_0} castShadow receiveShadow />
			<T.Mesh geometry={gltf.nodes.Object_5.geometry} material={gltf.materials.material_0} castShadow receiveShadow />
			<T.Mesh geometry={gltf.nodes.Object_6.geometry} material={gltf.materials.material_0} castShadow receiveShadow />
			<T.Mesh geometry={gltf.nodes.Object_7.geometry} material={gltf.materials.material_0} castShadow receiveShadow />
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
